feature: ['feature/*', 'feat/*', 'feature:*', 'feat:*', 'feature(*', 'feat(*']
fix: ['fix/*', 'fix:*', 'fix(*']
build: ['build/*', 'build:*', 'build(*']
documentation: ['documentation/*', 'doc/*', 'documentation:*', 'doc:*', 'documentation(*', 'doc(*']
style: ['style/*', 'style:*', 'style(*']
refactor: ['refactor/*', 'refactor:*', 'refactor(*']
performance: ['performance/*', 'performance:*', 'performance(*']
test: ['test/*', 'test:*', 'test(*']
chore: ['chore/*', 'chore:*', 'chore(*']
ci: ['ci/*', 'ci:*', 'ci(*']
